check ffmpeg return value

diff --git a/dlm3u8 b/dlm3u8
--- a/dlm3u8
+++ b/dlm3u8
@@ -50,7 +50,7 @@ fn_dlm3u8() {
   aria2c -i aria2c.txt
   if [[ $? -ne 0 ]]; then
     echo
-    echo "Download \"$url\" related files failed."
+    echo "Download \"$url\" related files errors."
     return 1
   fi
 
@@ -62,6 +62,10 @@ fn_dlm3u8() {
   echo
   echo "Generating \"$ffmpeglog\" for advertisement removal..."
   ffmpeg -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy -f null /dev/null > "$ffmpeglog" 2>&1
+  if [[ $? -ne 0 ]]; then
+    echo "Error: Generating \"$ffmpeglog\" file errors."
+    return 1
+  fi
 
   # generate fixed.m3u8 by ffmpeg log
   node "$(dirname "$0")/src/fixm3u8.js" "$input" "$ffmpeglog"
@@ -73,12 +77,10 @@ fn_dlm3u8() {
   echo
   echo "Merging \"$output\" based on \"$input\"..."
   ffmpeg -y -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy "$output" > ffmpeg.2.log 2>&1
-
-  # display output result
-  if [[ -f "$output" ]]; then
-    echo "Successfully wrote \"$output\" file."
+  if [[ $? -eq 0 ]]; then
+    echo "Successfully merge \"$output\" file."
   else
-    echo "Error: Failed to write \"$output\" file."
+    echo "Error: Merging \"$output\" file errors."
     return 1
   fi
   return 0
diff --git a/m3u8tomp4 b/m3u8tomp4
--- a/m3u8tomp4
+++ b/m3u8tomp4
@@ -48,6 +48,10 @@ input="$1"
 ffmpeglog="ffmpeg.1.log"
 echo "Generating \"$ffmpeglog\" for advertisement removal..."
 ffmpeg -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy -f null /dev/null > "$ffmpeglog" 2>&1
+if [[ $? -ne 0 ]]; then
+  echo "Error: Generating \"$ffmpeglog\" file errors."
+  exit 1
+fi
 
 # generate fixed.m3u8 by ffmpeg log
 node "$(dirname "$0")/src/fixm3u8.js" "$input" "$ffmpeglog"
@@ -59,11 +63,9 @@ fi
 echo
 echo "Merging \"$output\" based on \"$input\"..."
 ffmpeg -y -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy "$output" > ffmpeg.2.log 2>&1
-
-# display output result
-if [[ -f "$output" ]]; then
-  echo "Successfully wrote \"$output\" file."
+if [[ $? -eq 0 ]]; then
+  echo "Successfully merge \"$output\" file."
 else
-  echo "Error: Failed to write \"$output\" file."
+  echo "Error: Merging \"$output\" file errors."
   exit 1
 fi
